### ISSUE TITLE
Linux executable just pop a black screen

### ISSUE THREAD

**Issue by KGriss** [HemantKArya/BloomeeTunes#52]
When I open the executable from the Linux archive, it only opens a black window. Nothing more.
Tested with files from Github on different versions, including the latest one.

**Comment by HemantKArya** [comment]
Hi @KGriss thanx for submitting this issue I know it is late reply 🙂, But still...about your issue I don't know about linux archive one but here the latest version is working fine in XUbuntu OS.
![image](https://github.com/user-attachments/assets/7e2414ad-85f0-4466-b48b-dbc9f8d2b9dc)

I guess it may be not working in some Linux system, can you clarify more and what Flavor you are using? So that I can debug this issue for that system.

**Comment by KGriss** [comment]
I am using Fedora Workstation 40 and Gnome 46 as a desktop environnement. Tested with the last version of Bloomee and I still just get a black screen.

**Comment by HemantKArya** [comment]
In the meantime, if anyone has any insights on this issue or wishes to discuss related matters, please feel free to do so here.

**Comment by decepticlown** [comment]
Fedora uses wayland as default. @KGriss could you execute it from terminal and see what's printing and post it here?

**Comment by KGriss** [comment]
Just got this log using the latest version of Bloomee.
`package:media_kit_libs_linux registered.
flutter: 
--------------------------------------------------------------------------------
media_kit: ERROR: MediaKit.ensureInitialized
This indicates that one or more required dependencies could not be located.

Refer to "Installation" section of the README for further details:
GitHub  : https://github.com/media-kit/media-kit#installation
pub.dev : https://pub.dev/packages/media_kit#installation

TIP: Copy-paste required packages from the above link to your pubspec.yaml.

If you recently added the packages, make sure to re-run the project ("hot-restart" & "hot-reload" is not sufficient for native plugins).
--------------------------------------------------------------------------------

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: Cannot find libmpv at the usual places. Depending upon your distribution, you can install the libmpv package to make shared library available globally. On Debian or Ubuntu based systems, you can install it with: apt install libmpv-dev.
#0      NativeLibrary.ensureInitialized (package:media_kit/src/player/native/core/native_library.dart:78)
#1      nativeEnsureInitialized (package:media_kit/src/player/native/player/real.dart:47)
#2      MediaKit.ensureInitialized (package:media_kit/src/media_kit.dart:30)
#3      JustAudioMediaKit.ensureInitialized (package:just_audio_media_kit/just_audio_media_kit.dart:78)
#4      main (package:Bloomee/main.dart:109)
#5      _runMain.<anonymous closure> (dart:ui/hooks.dart:301)
#6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297)
#7      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)
`

**Comment by KGriss** [comment]
It seems that libmpv is missing, in addition to a flutter component `media_kit` ?

**Comment by mrcodefrost** [comment]
media_kit is not missing @KGriss @HemantKArya . It requires libmpv to work, in your case libmpv is the only thing missing which needs to be installed.
Same has been stated in the [media_kit docs](https://pub.dev/packages/media_kit).

![image](https://github.com/user-attachments/assets/d19e712e-7f30-4196-94a6-79f935a66c2f)


Solution : The bug should be fixed by running 

`
sudo apt install libmpv-dev mpv
`

**Comment by 3gsahil** [comment]
> media_kit is not missing [@KGriss](https://github.com/KGriss) [@HemantKArya](https://github.com/HemantKArya) . It requires libmpv to work, in your case libmpv is the only thing missing which needs to be installed. Same has been stated in the [media_kit docs](https://pub.dev/packages/media_kit).
> 
> ![image](https://github.com/user-attachments/assets/d19e712e-7f30-4196-94a6-79f935a66c2f)
> 
> Solution : The bug should be fixed by running
> 
> `sudo apt install libmpv-dev mpv`

did just that still the issue persists .

sudo apt install libmpv-dev mpv

[sudo] password for xahil: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libmpv-dev is already the newest version (0.34.1-1ubuntu3).
libmpv-dev set to manually installed.
mpv is already the newest version (0.34.1-1ubuntu3).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by HemantKArya** [comment]
Yeah sure I will create some kind of guide or installation tip file in the repo so that we guide people coming from different flavors of Linux system.
